baseURL = 'https://www.teaandrobots.com/'
languageCode = 'en-us'
title = 'Tea & Robots'
theme = "hello-friend"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false

[menu]
  [[menu.main]]
    identifier = "pages"
    name = "Pages"
    url = "/pages/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = 3
